// flow-typed signature: 7381c86c4510e1c89d3e8a311d139c81
// flow-typed version: <<STUB>>/eslint-config-unobtrusive_v^1.2.1/flow_v0.61.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-config-unobtrusive'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-config-unobtrusive' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-config-unobtrusive/fixtures/hasCJSDefaultExport' {
  declare module.exports: any;
}

declare module 'eslint-config-unobtrusive/fixtures/hasESDefaultExport' {
  declare module.exports: any;
}

declare module 'eslint-config-unobtrusive/fixtures/hasNamedCJSExport' {
  declare module.exports: any;
}

declare module 'eslint-config-unobtrusive/fixtures/hasNamedESExport' {
  declare module.exports: any;
}

declare module 'eslint-config-unobtrusive/flowtype' {
  declare module.exports: any;
}

declare module 'eslint-config-unobtrusive/import' {
  declare module.exports: any;
}

declare module 'eslint-config-unobtrusive/index.test' {
  declare module.exports: any;
}

declare module 'eslint-config-unobtrusive/react' {
  declare module.exports: any;
}

declare module 'eslint-config-unobtrusive/tests/basic' {
  declare module.exports: any;
}

declare module 'eslint-config-unobtrusive/tests/flowtype' {
  declare module.exports: any;
}

declare module 'eslint-config-unobtrusive/tests/import' {
  declare module.exports: any;
}

declare module 'eslint-config-unobtrusive/tests/react' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-config-unobtrusive/fixtures/hasCJSDefaultExport.js' {
  declare module.exports: $Exports<'eslint-config-unobtrusive/fixtures/hasCJSDefaultExport'>;
}
declare module 'eslint-config-unobtrusive/fixtures/hasESDefaultExport.js' {
  declare module.exports: $Exports<'eslint-config-unobtrusive/fixtures/hasESDefaultExport'>;
}
declare module 'eslint-config-unobtrusive/fixtures/hasNamedCJSExport.js' {
  declare module.exports: $Exports<'eslint-config-unobtrusive/fixtures/hasNamedCJSExport'>;
}
declare module 'eslint-config-unobtrusive/fixtures/hasNamedESExport.js' {
  declare module.exports: $Exports<'eslint-config-unobtrusive/fixtures/hasNamedESExport'>;
}
declare module 'eslint-config-unobtrusive/flowtype.js' {
  declare module.exports: $Exports<'eslint-config-unobtrusive/flowtype'>;
}
declare module 'eslint-config-unobtrusive/import.js' {
  declare module.exports: $Exports<'eslint-config-unobtrusive/import'>;
}
declare module 'eslint-config-unobtrusive/index' {
  declare module.exports: $Exports<'eslint-config-unobtrusive'>;
}
declare module 'eslint-config-unobtrusive/index.js' {
  declare module.exports: $Exports<'eslint-config-unobtrusive'>;
}
declare module 'eslint-config-unobtrusive/index.test.js' {
  declare module.exports: $Exports<'eslint-config-unobtrusive/index.test'>;
}
declare module 'eslint-config-unobtrusive/react.js' {
  declare module.exports: $Exports<'eslint-config-unobtrusive/react'>;
}
declare module 'eslint-config-unobtrusive/tests/basic.js' {
  declare module.exports: $Exports<'eslint-config-unobtrusive/tests/basic'>;
}
declare module 'eslint-config-unobtrusive/tests/flowtype.js' {
  declare module.exports: $Exports<'eslint-config-unobtrusive/tests/flowtype'>;
}
declare module 'eslint-config-unobtrusive/tests/import.js' {
  declare module.exports: $Exports<'eslint-config-unobtrusive/tests/import'>;
}
declare module 'eslint-config-unobtrusive/tests/react.js' {
  declare module.exports: $Exports<'eslint-config-unobtrusive/tests/react'>;
}
